---
- name: Copy artifact.tar.gz to EC2
  become: True
  unarchive:
    src: "artifact.tar.gz"
    dest: "/home/ubuntu/artifact.tar.gz"

- name: Start app
  become: True
  shell: |
    cd /home/ubuntu/
    tar -xvf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start